#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : R-mirt
Version  : 1.44.0
Release  : 49
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/mirt_1.44.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/mirt_1.44.0.tar.gz
Summary  : Multidimensional Item Response Theory
Group    : Development/Tools
License  : GPL-3.0
Requires: R-mirt-lib = %{version}-%{release}
Requires: R-Deriv
Requires: R-GPArotation
Requires: R-Rcpp
Requires: R-RcppArmadillo
Requires: R-SimDesign
Requires: R-dcurver
Requires: R-gridExtra
Requires: R-pbapply
Requires: R-vegan
BuildRequires : R-Deriv
BuildRequires : R-GPArotation
BuildRequires : R-Rcpp
BuildRequires : R-RcppArmadillo
BuildRequires : R-RcppArmadillo-dev
BuildRequires : R-SimDesign
BuildRequires : R-dcurver
BuildRequires : R-gridExtra
BuildRequires : R-pbapply
BuildRequires : R-vegan
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
unidimensional and multidimensional item analysis models under the Item

%package lib
Summary: lib components for the R-mirt package.
Group: Libraries

%description lib
lib components for the R-mirt package.


%prep
%setup -q -n mirt
pushd ..
cp -a mirt buildavx2
popd
pushd ..
cp -a mirt buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738167720

%install
export SOURCE_DATE_EPOCH=1738167720
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/mirt/CITATION
/usr/lib64/R/library/mirt/DESCRIPTION
/usr/lib64/R/library/mirt/INDEX
/usr/lib64/R/library/mirt/Meta/Rd.rds
/usr/lib64/R/library/mirt/Meta/data.rds
/usr/lib64/R/library/mirt/Meta/features.rds
/usr/lib64/R/library/mirt/Meta/hsearch.rds
/usr/lib64/R/library/mirt/Meta/links.rds
/usr/lib64/R/library/mirt/Meta/nsInfo.rds
/usr/lib64/R/library/mirt/Meta/package.rds
/usr/lib64/R/library/mirt/Meta/vignette.rds
/usr/lib64/R/library/mirt/NAMESPACE
/usr/lib64/R/library/mirt/NEWS.md
/usr/lib64/R/library/mirt/R/mirt
/usr/lib64/R/library/mirt/R/mirt.rdb
/usr/lib64/R/library/mirt/R/mirt.rdx
/usr/lib64/R/library/mirt/data/Rdata.rdb
/usr/lib64/R/library/mirt/data/Rdata.rds
/usr/lib64/R/library/mirt/data/Rdata.rdx
/usr/lib64/R/library/mirt/doc/index.html
/usr/lib64/R/library/mirt/doc/mirt-vignettes.Rmd
/usr/lib64/R/library/mirt/doc/mirt-vignettes.html
/usr/lib64/R/library/mirt/help/AnIndex
/usr/lib64/R/library/mirt/help/aliases.rds
/usr/lib64/R/library/mirt/help/mirt.rdb
/usr/lib64/R/library/mirt/help/mirt.rdx
/usr/lib64/R/library/mirt/help/paths.rds
/usr/lib64/R/library/mirt/html/00Index.html
/usr/lib64/R/library/mirt/html/R.css
/usr/lib64/R/library/mirt/tests/testthat/test-00-basics.R
/usr/lib64/R/library/mirt/tests/testthat/test-01-mirtOne.R
/usr/lib64/R/library/mirt/tests/testthat/test-02-mirtTwo.R
/usr/lib64/R/library/mirt/tests/testthat/test-03-bfactor.R
/usr/lib64/R/library/mirt/tests/testthat/test-04-multipleGroup.R
/usr/lib64/R/library/mirt/tests/testthat/test-05-confmirtOne.R
/usr/lib64/R/library/mirt/tests/testthat/test-06-confmirtTwo.R
/usr/lib64/R/library/mirt/tests/testthat/test-07-mixedmirt.R
/usr/lib64/R/library/mirt/tests/testthat/test-08-createItem.R
/usr/lib64/R/library/mirt/tests/testthat/test-09-mirt.model.R
/usr/lib64/R/library/mirt/tests/testthat/test-10-extras.R
/usr/lib64/R/library/mirt/tests/testthat/test-11-discrete.R
/usr/lib64/R/library/mirt/tests/testthat/test-12-gpcm_mats.R
/usr/lib64/R/library/mirt/tests/testthat/test-13-grsmIRT.R
/usr/lib64/R/library/mirt/tests/testthat/test-14-unfolding.R
/usr/lib64/R/library/mirt/tests/testthat/test-15-IRTpars.R
/usr/lib64/R/library/mirt/tests/testthat/test-16-DCIRT.R
/usr/lib64/R/library/mirt/tests/testthat/test-17-DIF_DRF.R
/usr/lib64/R/library/mirt/tests/testthat/test-18-LLTM.R
/usr/lib64/R/library/mirt/tests/testthat/testdata/MG1.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/MG2.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/MG3.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/bfactor1.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/bfactor2.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/conftwo1.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/dcirt1.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/dcirt2.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/dcirt3.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/dif1.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/discrete1.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/extras1.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/mixed1.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/mixed2.rds
/usr/lib64/R/library/mirt/tests/testthat/testdata/rst.rds

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/mirt/libs/mirt.so
/V4/usr/lib64/R/library/mirt/libs/mirt.so
/usr/lib64/R/library/mirt/libs/mirt.so
